version: '3.8'
services:
  db:
    image: mysql
    container_name: bdapp
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  estoque:
    image: lucasrudyson/estoque:1.0
    container_name: myapp
    links:
      - "db"
    ports:
      -  "5001:5000" 
