version: '3.8'
services:
  db:
    image: mysql
    container_name: petsbd
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pets
    


  estoque:
    container_name: estoque
    links:
      - "db"
    build: ./
    ports:
      -  "5001:5000" 

        