version: '3.8'
services:
  db:
    image: mysql
    container_name: petsbd
    ports:
      - "32001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pets
    command: docker exec -i petsbd mysql -uroot -ppets < banco/script.sql


  estoque:
    container_name: myapp
    links:
      - "db"
    build: ./
    ports:
      -  "5001:5000" 

        